### ISSUE TITLE
Not working when html5Mode is enabled for routing

### ISSUE THREAD

**Issue by bvuden** [JamesRandall/AngularJS-OAuth2#1]
Hi,

When html5Mode for routing is enabled in AngularJS the url param that is received after login starts with a hash (f.e. http://localhost:1881/#access_token=). Because of this the acces_token is not retrieved from the url parameter.
I implemented a quick fix in service.set:

``` javascript
if (hashValues.indexOf('#/') == 0) {
hashValues = hashValues.substring(2);
```

to

``` javascript
if (hashValues.indexOf('#') == 0) {
hashValues = hashValues.substring(1);
```

This  fixed the issue for me.
Maybe you can add an option to the directive for html5Mode?

Cheers,
Bart

**Comment by JamesRandall** [comment]
Hi Bart,

Good idea - I'll do that. Thanks.

James

**Comment by bvuden** [comment]
Thanks!
Nice plugin by the way, i'm using it in a small project right now.

Bart

**Comment by JamesRandall** [comment]
Hi Bart,

I've fixed the HTML5 routing issue. The directive will detect the routing mode and behave accordingly.

James
