### ISSUE TITLE
Ionic and Apache Cordova 

### ISSUE THREAD

**Issue by tomek14** [JamesRandall/AngularJS-OAuth2#10]
Hi,
Did somebody tried to use this plugin with standard Ionic Framework template for Apache Cordova? Because when I'm tring to use it with IdentityServer3 authentication works fine, i am able to log in, but the button don't change to "SingOut". Did somebody have this issue?

**Comment by JamesRandall** [comment]
Hi Tomek,

I've not tried this but am about to start a new project in Ionic that will use this plugin. I'll try it against my sample project and investigate - hopefully will be able to this weekend.

James

**Comment by JamesRandall** [comment]
It took me a while to look into this and I realised there is a (non code) problem. Apple reject app's from the store that have embedded browsers with external links in - even identity / login pages (I know from painful personal experience). My solution to this is to launch an external browser on iOS and to register a custom app UNC (myapp: for example) in the info.plist file and in IdentityServer (i.e. my callback / redirect URI is myapp://).

In Android I use the embedded browser but take the same basic approach.

I'll try and post an example at some point.
