### ISSUE TITLE
Revoke token

### ISSUE THREAD

**Issue by markoradinovic** [JamesRandall/AngularJS-OAuth2#11]
Hi,
I'm having trouble implementing revoke token functionality.

I find the problem in this method:

```
scope.signOut = function() {
        var token = accessToken.get().id_token;
        accessToken.destroy();
        endpoint.signOut(token);
};
```

token variable is always null;

I think it should be:

```
var token = accessToken.get().access_token;
```

Thank You for your great library.

Best regards,

Marko Radinovic

**Comment by JamesRandall** [comment]
Thanks Marko - I'll look to get that included shortly

**Comment by BennyEmmers** [comment]
This is caused when you do not include id_token in the response-type property of the oauth directive. You also have to include openId in the scope of the directive and in the scopes of the STS. If you would use access_token instead the redirect back to the SPA, after the logout page, will not work.
