### ISSUE TITLE
Publish token information with successful auth event

### ISSUE THREAD

**Issue by pinnprophead** [JamesRandall/AngularJS-OAuth2#17]
This isn't really an issue, but it would be nice if the token information was published in the authSuccess event. A simple change:

```
        $rootScope.$broadcast('oauth2:authSuccess', service.token);
```

That way use of the token does not need to be tightly coupled to the library services.

Common use would be to extract the preferred name or email address from the identity token.

**Comment by JamesRandall** [comment]
Agreed - that would make sense, I'll get it added.

**Comment by JamesRandall** [comment]
I've added this to v1.0.3.
