### ISSUE TITLE
Interceptor doesn't handle badrequest response properly

### ISSUE THREAD

**Issue by bvuden** [JamesRandall/AngularJS-OAuth2#2]
Hi James,

When a badrequest (status 400) response comes through the interceptor it is not rejected.
As a result any client side validation messages will not be displayed and the user will be forwarded to the service method's succes route.
You can see the fix in my fork if you want to.

Cheers,
Bart

**Comment by JamesRandall** [comment]
Thanks Bart - I noticed myself and by the looks of it fixed it simultaneously with the same fix. I've also updated it today so that if you have route params they carry through across the redirect.
