### ISSUE TITLE
Provide tags that match the bower.json

### ISSUE THREAD

**Issue by ciaranj** [JamesRandall/AngularJS-OAuth2#25]
I _think_ that I'm having problems using bower with the library as there are no tags that match the versions you're specifying in the bower.json currently.  This is important for me as I need to shrinkwrap/freeze the versions of the libraries which I depend upon.    I don't need any historical versions but one matching the current 'released' version would be rather handy for me please :)

**Comment by JamesRandall** [comment]
Odd. Not sure what's happened there - I'll take a look tomorrow.

**Comment by JamesRandall** [comment]
Thanks for letting me know!

**Comment by JamesRandall** [comment]
I've added a tag for the latest version, let me know if it doesn't resolve your issue.

**Comment by ciaranj** [comment]
Well, it does resolve it, but you have to specify the versions as 'v1.0.5' rather than '1.0.5'.  I'm not sure if that was your intention (and I'm even less sure if that's really very semver) ?

**Comment by JamesRandall** [comment]
I took a look at the bower docs (which says "Your package should use semver Git tags. The v prefix is allowed.") and a number of popular bower packages when doing this (bootstrap, angular itself) - they mostly seem to use a non-prefixed version in the bower.json (so 1.0.5) and a v prefix on the release.

Bower itself seems to understand the v in the release - if I do a bower info angularjs-oauth2 it gives me the output I'd expect (available releases 1.0.5).

Am I misunderstanding something?

**Comment by ciaranj** [comment]
hmmm, well I guess then all is good on your side.  But on my side if I reference in my consuming bower.json "1.0.5" bower doesn't locate your library (or that version at least) if I reference "v1.0.5" it does.    _HOWEVER_ I use a private NPM repository (https://github.com/rlidwka/sinopia) so perhaps that isn't respecting things correctly.  Let's assume what you've done is right and I'll either just reference with a 'v' in my bower.json or look deeper into sinopia's workings :)

**Comment by JamesRandall** [comment]
I've got to upgrade a couple of projects myself in the coming days - I'll dig a little deeper myself as I do so.
