### ISSUE TITLE
Make the library available on NPM

### ISSUE THREAD

**Issue by linsolas** [JamesRandall/AngularJS-OAuth2#29]
Hello,

Thanks for your work on this interesting project.
On our side, we do not use Bower, but "just" npm. Shouldn't it be convenient for developers who are not using Bower, to make the library available on npmjs.org?

Note that there is already a project called [`angular-oauth2`](https://www.npmjs.com/package/angular-oauth2), which has a name qui similar to this project...

**Comment by JamesRandall** [comment]
Hi,

Thanks for the feedback - sounds like a good idea. I'll look to get that done in the next few days.

**Comment by ducks** [comment]
Any update on an npm package being available? I would like to install this with npm as well. I am willing to lend a hand if needed.

**Comment by JamesRandall** [comment]
Sorry - totally slipped my mind. I've just released it as an npm.

If you find any issues with the packaging then let me know.
