### ISSUE TITLE
Nonce required for openId with IdentityServer3

### ISSUE THREAD

**Issue by pinnprophead** [JamesRandall/AngularJS-OAuth2#4]
I think a nonce (number used once) attribute would be required for IdentityServer3. When asking for openid scope, IdentityServer3 returns an error that says "nonce required."

The thinktecture guys had this handy function for the (default) value of nonce:

function rand() {
   return ((Date.now() + Math.random()) \* Math.random()).toString().replace(".","");
}

They used it for the "state" value as well.

**Comment by pinnprophead** [comment]
I made minor changes to the component, tested and it works with the nonce attribute (and default value) added.

**Comment by JamesRandall** [comment]
Thank pinnprophead - I'll get a fix in place hopefully this weekend.

**Comment by JamesRandall** [comment]
Now in the package and I've tested it with IdentityServer3 functions that require state.
