### ISSUE TITLE
Not able to catch interceptor broadcasts

### ISSUE THREAD

**Issue by rndthoughts** [JamesRandall/AngularJS-OAuth2#6]
Something seems to be wrong with my broadcast wireups.  When the auth server redirects back, the broadcasts are fired before the scope.$on functions are wired up in the directive therefore they don't fire?

**Comment by JamesRandall** [comment]
Have you got a code sample you can point me at and I'll take a look?

**Comment by JamesRandall** [comment]
Closing as can't replicate.
