### ISSUE TITLE
Examples for IdentityServer3

### ISSUE THREAD

**Issue by mnewboult** [JamesRandall/AngularJS-OAuth2#8]
Hi,

I've just read your post (http://www.azurefromthetrenches.com/?p=2241) and found it very helpful. You mention in your blog that you got your directive working with IdentityServer3. You link to a Github of a sample using Google for your identity server, do you have an example I can see using Identity Server?

Also, do you think it would be easy to implement the routing in ui-router?

Any help appreciated.

Thanks,

Matt

**Comment by JamesRandall** [comment]
Hi Matt,

Time allowing I'm hoping to put together a sample this weekend that includes the simplest in-memory variant of IdentityServer3, a Web API and an AngularJS front end.

I've used ui-router as part of Ionic (but somewhat simplistic) and I figure it should be possible to replicate the requireToken behaviour by using the $stateChangeStart event. Again if I get a chance I'll take a look at this.

James

**Comment by mnewboult** [comment]
Hi James,

Thanks for the reply. We're looking into IDS at our company and have
managed to get all but the Javascript version working (got MVC and WebApi
apps working). I look forward to your sample. We're also thinking of trying
to make ui-router use the claims that come back from IDS3 to authorise the
routes. We're all .Net devs but newish to Angular so it's a bit of a
journey of discovery at the moment.

Thanks for your work putting this out there - much appreciated.

Matt

On 25 June 2015 at 22:32, James Randall notifications@github.com wrote:

> Hi Matt,
> 
> Time allowing I'm hoping to put together a sample this weekend that
> includes the simplest in-memory variant of IdentityServer3, a Web API and
> an AngularJS front end.
> 
> I've used ui-router as part of Ionic (but somewhat simplistic) and I
> figure it should be possible to replicate the requireToken behaviour by
> using the $stateChangeStart event. Again if I get a chance I'll take a look
> at this.
> 
> James
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/JamesRandall/AngularJS-OAuth2/issues/8#issuecomment-115404788
> .

## 

---

Matt Newboult
email : mnewboult@gmail.com
blog: www.theonology.com
twitter: http://twitter.com/mnewboult

**Comment by JamesRandall** [comment]
Hi Matt,

I've put a sample in GitHub here:

https://github.com/JamesRandall/AngularJS-OAuth2-IdentityServer3-Sample

Hope that's useful.

James

**Comment by mnewboult** [comment]
Thanks. Will take a look.

On 27 June 2015 at 19:22, James Randall notifications@github.com wrote:

> Hi Matt,
> 
> I've put a sample in GitHub here:
> 
> https://github.com/JamesRandall/AngularJS-OAuth2-IdentityServer3-Sample
> 
> Hope that's useful.
> 
> James
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/JamesRandall/AngularJS-OAuth2/issues/8#issuecomment-116114247
> .

## 

---

Matt Newboult
email : mnewboult@gmail.com
blog: www.theonology.com
twitter: http://twitter.com/mnewboult
